In [347]:
import numpy as np

배열 만들기

In [348]:
a = np.array([[10, 9, 8], [1, 2, 3]])

a

array([[10,  9,  8],
       [ 1,  2,  3]])

배열 만들기

In [349]:
ar1 = np.array([[1., 2., 3., 4.], [4., 3., 2., 1.]], dtype=float)
ar2 = np.array([[1, 2, 3, 4], [4, 3, 2, 1], [1, 2, 3, 4], [4, 3, 2, 1]], dtype="int8")

ar1

array([[1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [350]:
ar1

array([[1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [351]:
ar1.shape

(2, 4)

In [352]:
ar1.ndim

2

In [353]:
ar2

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [4, 3, 2, 1]], dtype=int8)

In [354]:
ar2.shape

(4, 4)

In [355]:
ar2.ndim

2

reshape

In [356]:
b = np.array([1, 2, 3, 4, 5, 6], dtype=int)
b

array([1, 2, 3, 4, 5, 6])

In [357]:
b.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [358]:
b.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [359]:
b.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [360]:
c = np.arange(60)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [361]:
c.reshape(-1, 10) # -1의 의미

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [362]:
d = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]])
e = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
d
e

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [363]:
d[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [364]:
d[[1,3], :4]

array([[ 5,  6,  7,  8],
       [15, 16, 17, 18]])

In [365]:
d[:, 3:4]

array([[ 3],
       [ 8],
       [13],
       [18]])

In [366]:
e[1:4, 0:3]

array([[5, 6, 7],
       [0, 1, 2],
       [5, 6, 7]])

In [367]:
f = np.array([np.array(np.arange(12)),np.array(np.arange(12,24))]) #.reshape(2, 12)
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [368]:
g = f[0:2, ::4]
g

array([[ 0,  4,  8],
       [12, 16, 20]])

In [369]:
h = np.array([[1, 4, 7], [10, 13, 16], [19, 22, 25], [28, 31, 34]])
i = np.array([1, 2, 3, 4])

In [370]:
k = i.reshape(4, 1)
k

array([[1],
       [2],
       [3],
       [4]])

In [371]:
h + k

array([[ 2,  5,  8],
       [12, 15, 18],
       [22, 25, 28],
       [32, 35, 38]])

In [ ]:
q = np.arange(20).reshape(4, 5)
w = np.array([[5, 5, 5, 5, 5], [5, 5, 5, 5, 5], [15, 15, 15, 15, 15], [15, 15, 15, 15, 15]])
q>w

슬라이싱

In [ ]:
ar1 = np.array(range(10))

print(ar1)
print(ar1[:]) #전체 출력
print(ar1[:4]) # 4번 인덱스까지
print(ar1[2:]) # 2번 인덱스 부터
print(ar1[3:8]) # 3번부터 7번까지
print(ar1[::2]) # 처음부터 끝까지 두칸씩
print(ar1[2:9:3]) # 2부터 8까지 3칸씩