In [397]:
import numpy as np

x = np.arange(1, 10001)
x

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [398]:
y = np.arange(10001, 20001)
y

array([10001, 10002, 10003, ..., 19998, 19999, 20000])

In [399]:
%time

z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i] 

CPU times: total: 0 ns
Wall time: 0 ns


In [400]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

<h5>백터화 연산 사용</h5>

In [401]:
%time

z = x + y

# 백터화 연산이 더 빠름

CPU times: total: 0 ns
Wall time: 0 ns


<h3>백터화 연산</h3>

In [402]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

a + b

array([5, 4, 5, 8])

In [403]:
a == b      # 논리 연산도 가능

array([False,  True, False,  True])

In [404]:
np.all(a == b)       # all 명령 사용

False

<h5>모든 요소 적용되는 일반 연산</h5>

In [405]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [406]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [407]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [408]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [409]:
100 * a

array([  0, 100, 200, 300, 400])

<h5>브로드캐스팅</h5>

In [410]:
x = np.array([[0, 1, 2,], [1, 2, 3,], [2, 3, 4], [3, 4, 5], [4, 5, 6]])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [411]:
y = np.array([[0], [1], [2], [3], [4]])
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [412]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [413]:
y = np.arange(3)
y
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

<h5>차원 축소 연산</h5>

차원 축소 연산

1차원 배열에 대해 평균을 구하면 상수 값(0차원)이 반환됨
2차원 배열에서 각열에 대한 평균을 구하면 1차원 배열이 반환됨

최대/최소 [min, maxm argmin, argmax]

통계      [sum, mean, median, std, var]

불리언    [all(전부 참), any(하나라도 참)]

In [414]:
x = np.array([1, 2, 3, 4])

x

array([1, 2, 3, 4])

In [415]:
x.sum()

10

In [416]:
x.min()

1

In [417]:
x.argmin()

0

In [418]:
np.median(x)

2.5

In [419]:
np.any([True, True, False])

True

In [420]:
x = np.array([1, 2, 3, 4,])

x

x.sum()
x.min()
x.max()
x.argmin() # 최소값 위치
x.argmax() # 최대값 위치

np.median(x)
np.mean(x)
np.std(x)
np.std(x)
np.var(x)

np.all([True, True, False])

False

In [421]:
a = np.zeros((100, 100), dtype=np.int32)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [422]:
np.any(a != 0)

False

In [423]:
np.all(a == 0)

True

In [424]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

In [425]:
x = np.array([[1,1],[2, 2]])

x

array([[1, 1],
       [2, 2]])

In [426]:
x.sum()

6

In [427]:
x.sum(axis = 0)     # 열 합계

array([3, 3])

In [428]:
x.sum(axis = 1)     # 행 합계

array([2, 4])

<h3>연습문제 1.6</h3>

In [429]:
ee = np.array([[1, 4, 1, 4], [2, 5, 2, 5], [3, 6, 3, 6], [1, 4, 1, 4], [2, 5, 2, 5], [3, 6, 3, 6]])
ee

array([[1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6],
       [1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6]])

In [430]:
ee.max()        # 전체의 최댓값

6

In [431]:
ee.sum(axis = 1)        # 각 행의 합

array([10, 14, 18, 10, 14, 18])

In [432]:
ee.max(axis = 1)        # 각 행의 최댓값

array([4, 5, 6, 4, 5, 6])

In [433]:
ee.mean(axis = 0)       # 각 열의 평균

array([2., 5., 2., 5.])

In [434]:
ee.min(axis = 0)        # 각 열의 최솟값

array([1, 4, 1, 4])