<h1>배열의 연결</h1>
<h3>hstack 행의 수가 같은 배열을 옆으로 연결 (horizontal)</h3>

In [7]:
import numpy as np

a1 = np.ones((2, 3))
a2 = np.zeros((2, 3))

np.hstack([a1, a2])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

<h3>vstack 열의 수가 같은 배열을 아래위로 연결 (vertical)</h3>

In [8]:
b1 = np.ones((2, 3))
b2 = np.zeros((3 ,3))

np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<h3>dstack 행과 열이 아닌 깊이 방향으로 배열</h3>

In [9]:
c1 = np.ones((3, 4))
c2 = np.zeros((3, 4))

np.dstack([c1, c2])
(np.dstack([c1, c2])).shape

(3, 4, 2)

<h3>stack 앞의 dstack 매서드의 확장 기능 제공</h3>
<h3>axis 인수 (기본값 0)를 지정하여 지정한 인수로 차원을 확장</h3>

In [11]:
c = np.stack([c1, c2], axis = 1)      # axis = 0 열 단위 1 행 단위
c
c.shape

(3, 2, 4)

<h3>tile 동일한 배열을 반복하여 연결</h3>

In [12]:
a = np.array(([0, 1, 2], [3, 4, 5]))
np.tile(a, 2)

np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

<h3>연습문제</h3>

In [13]:
h1 = np.array([[1, 4], [2, 5], [3, 6], [1, 4], [2, 5], [3, 6]])
v2 = np.array([[1, 4, 1, 4], [2, 5, 2, 5], [8, 6 ,3 ,6]])
t2 = np.array([[1, 4], [2, 5], [3, 6]])

np.hstack([h1, h1])
np.vstack([v2, v2])
np.tile(t2, (2, 2))

array([[1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6],
       [1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6]])